### ISSUE TITLE
Preserve lower/upper case for various names and keywords

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#102]
The request
```fortls --debug_rootpath . --debug_hover --debug_filepath test8.f90 --debug_line 11 --debug_char 14```

 for the small code sample below gives:
```
  Result:
=======
SUBROUTINE MY_sub(self, my_var)
 CLASS(ttabc), INTENT(IN) :: Self
 INTEGER :: My_Var
=======
```

In some cases upper/lower case is preserved, in other cases it is lost.
It would also be nice to preserve exact case of keywords like SUBROUTINE, which is sometimes all uppercase, sometimes all lowercase or something in between.

test8.f90:
```
module mod

implicit none

type :: tTaBc
   integer :: mY_vAr
contains
   procedure :: MY_sub
end type t

Subroutine MY_sub(Self, My_Var)
   class(tTaBc), intent(in) :: Self
   integer :: My_Var
   self%mY_vAr = My_Var
End Subroutine MY_sub

end module mod
```

**Comment by hansec** [comment]
This was a design decision for visual consistency of keywords, since Fortran is case insensitive anyways. I try to preserve case everywhere for variables/subroutines/types and other user defined items since many people find this useful (ex. camelCase) even if it isn't strictly "recognized" in Fortran.

Is you interest in preserving case for keywords purely aesthetic or do you use keyword case to distinguish definitions in some way?

**Comment by mscfd** [comment]
Yeah, my pretty minor interest in preserving case of keywords is purely aesthetic. Case-insensitivity of fortran is a real pain...

**Comment by hansec** [comment]
Yeah, I agree. Case preservation for user-defined objects should now be fixed in master and will be included in the next patch. So the hover request should display as stated in my comment above.

**Comment by mscfd** [comment]
Thanks, works great.
