### ISSUE TITLE
Rename fails to rename implementation reference

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#104]
For the code below, the rename request at line 7, charpos 22, fails to rename in line 12. For some reason
```fortls --debug_rootpath . --debug_rename new_name --debug_filepath testB.f90 --debug_line 7 --debug_char 22```
fails with some python error. However, lsp-rename from emacs succeeds in renaming the references on line 7 and 14, but fails on 12 as mentioned.

Also invoking the rename request at line 14, charpos 20 fails the same. But rename at line 12, charpos 20 works.

testB.f90:
```
module mod

implicit none

type :: t
contains
   procedure :: to_be_renamed
end type t

contains

   subroutine to_be_renamed(self)
      class(t), intent(in) :: self
      call self%to_be_renamed()
   end subroutine to_be_renamed

end module mod
```

**Comment by hansec** [comment]
Thanks for the report! This should now be fixed in master and will be included in the next patch. Let me know if you run into any issues.

Please note that change requests are limited to a given object and will not "move through" the link. Therefore an explicit link will be added to the type-binding line to support a consistent rename on one side of the link. For example if you rename the subroutine the link line will become `procedure :: to_be_renamed => new_name`.
