### ISSUE TITLE
Handling of different file endings

### ISSUE THREAD

**Issue by PaulOxxx1** [hansec/fortran-language-server#108]
In my project, fortran source files with the ending ".h" are used and unfortunately I can't change the file extension. Is it possible to add my own file extensions that are parsed by the language server?

(Maybe I just haven't found the correct place to enter them, if so just let me know)

**Comment by hansec** [comment]
Are all files with the extension `*.h` in your project Fortran files? Also, is it just a few files or the most of the project? I am trying to decide whether it is best to add support for specifying an extension or just allowing you to specify specific files to treat as Fortran similar to [how files are excluded](https://github.com/hansec/fortran-language-server#configuration).

**Comment by PaulOxxx1** [comment]
In my project, all files with `*.h` extension are indeed fortran files.

For some reason, the people on my project decided to use this file ending for module files, which means this only concerns very few files. The majority of the files in the project has an `*.fpp` ending.

For my use case, doing this in the same way as the exclusion of files would be fine!

**Comment by hansec** [comment]
This is a little more involved than I initially thought because for things to work, in addition to the language server side, the client (text editor) also needs to be informed properly about which files to monitor. Although there are mechanisms for this in newer specifications of the protocol not all editors support this. What editor are you using? I want to make sure whatever solution I develop works for you at least.

**Comment by PaulOxxx1** [comment]
I'm using Visual Studio Code
