### ISSUE TITLE
Installation on mac has a problem

### ISSUE THREAD

**Issue by DrK** [hansec/fortran-language-server#12]
Installation with pip as instructed returns:

Processing ./fortran-language-server-0.3.4.tar.gz
Collecting future (from fortran-language-server==0.3.4)
  Could not fetch URL https://pypi.python.org/simple/future/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement future (from fortran-language-server==0.3.4) (from versions: )
No matching distribution found for future (from fortran-language-server==0.3.4)

Hopefully the above means something to someone
I have python 2.7.14 installed

Thanks, in anticipation

**Comment by hansec** [comment]
This is actually an issue with `pip` not the package. The issue is that the version of `pip` you have installed is old and uses a version of SSL that is no longer supported by The Python Package Index (where `pip` pulls packages from). The relevant error is

    Could not fetch URL https://pypi.python.org/simple/future/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping

To fix this you need to upgrade your version of `pip`. See this [stack overflow answer](https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies-th/49748494#49748494) for more information and instructions.
