### ISSUE TITLE
Can't upgrade to 1.10.3

### ISSUE THREAD

**Issue by PaulOxxx1** [hansec/fortran-language-server#146]
I don't know whether this issue comes from the Fortran-Language-Server code or whether my system isn't properly configured. I can uninstall and install version 1.10.2 without a problem.

<img width="1243" alt="Screenshot 2019-10-29 at 09 19 07" src="https://user-images.githubusercontent.com/12044204/67749394-5fd86400-fa2d-11e9-9e16-4fc96a3fae65.png">

**Comment by plevold** [comment]
I get the same error message on my system. I think it sounds like an error with the way it is packaged, but I could be wrong as know very little about packaging Python code :)

Here's some information about my installation:
```
$ pip --version
pip 1.5.6 from /opt/continuum/anaconda3.4/lib/python3.4/site-packages (python 3.4)
```

**Comment by hansec** [comment]
Sorry about that, this is most likely due to an old version of `setuptools`. The [README](https://github.com/hansec/fortran-language-server#installation) now has information on how to fix this error (courtesy of @phil-blain). If you run into issues with that fix or it doesn't work for you let me know.

**Comment by plevold** [comment]
Worked perfectly for me. By the way, thanks for maintaining this tool. Dealing with Fortran code is so much more pleasant when using it!
