### ISSUE TITLE
Unable to get Distribution.from_name(distribution_name)

### ISSUE THREAD

**Issue by moritzgubler** [hansec/fortran-language-server#224]
Hi

I just installed the fortran-language-server in combination with the atom package fortran-ide. However, atom is not able to start the fortran language server successfully. The following error appears:

IDE-Fortran: language server stopped unexpectedly.

return Distribution.from_name(distribution_name) File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name raise PackageNotFoundError(name) importlib.metadata.PackageNotFoundError: fortran-language-server

I am using openSUSE tumbleweed. Do you have an idea what could cause this? Thanks for looking into it.

**Comment by gnikit** [comment]
The atom extensions have not been getting updates for many years now, similar to the `fortran-language-server` project. We have shifted instead to VScode, modern fortran extension and fortls language server.

At some point I will have to write a new atom extension, but unfortunately it's not very high up in my to-do list.


Having said that I suspect the error that you are seeing is because you have not installed the server. You can check out the install instructions.

Not sure if that is helpful

**Comment by moritzgubler** [comment]
Thanks for your reply. I installed the server. I will look into migrating my projects to VScode then.

**Comment by moritzgubler** [comment]
I have just noticed, that the error only occurs in the flatpak version of atom. When I install atom with my package manager, the fortran-language-server can be successfully started.
