### ISSUE TITLE
"block" structure not detected

### ISSUE THREAD

**Issue by PaulXiCao** [hansec/fortran-language-server#23]
BRIEF: the language server fails to detect the "block" structure.
VERSION: 0.6.2

example file:
```
program blockTest
  implicit none
  real, parameter :: x=1.1
  block
    integer, parameter :: x=2
  end block
end program blockTest
```

The language server raises an error "Variable "x" declared twice in this scope".

**Comment by hansec** [comment]
I have just merged in an update, which should fix this issue in the next release. However, note that you will still get a warning (not an error) for the example you gave since the variable defined in the block and parent program have the same name. This variable masking can cause issues so I provide a warning in those cases.
