### ISSUE TITLE
Find references for type members is empty

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#88]
For the code below (named test.f90), the following gives no results:
fortls --debug_rootpath . --debug_references --debug_filepath test.f90 --debug_line 5 --debug_char 18

The position is on bar, and this should give the call self%bar line, right?

```
module mod

type x
contains
   procedure :: bar
end type x

contains

subroutine bar(self, some_arg)
   class(x) :: self
   real :: some_arg
   call self%bar(some_arg)
end subroutine bar
end module mod
```

**Comment by hansec** [comment]
Yes, this is intentional. Find references support for type members is not currently available as mentioned in the [README](https://github.com/hansec/fortran-language-server#language-server-features). I plan to add this soon, it is pretty straightforward except for how to handle inheritance in a consistent and expected way.

**Comment by mscfd** [comment]
Sorry, I have missed that, as I was not that interested in the animated gifs.

What is the problem with inheritance? For a type bound procedure sub of some type t, I would expect any invoking of x%sub() for x of some type s  which extends t (in one or more steps). Then all types which extend t and override sub. Are there any other kind of references?

**Comment by hansec** [comment]
Yeah, it's just a little more nuanced. Say you have the structure below. I agree with you that if I look for references to `test_parent::foo` then I should provide both `obj1%foo()` and `obj2%foo()` as results. However, if I instead look for references to `foo` in the line `CALL obj2%foo()` should it include references to `foo` in variables of the parent type as well (ie. `test_parent::foo`)? Personally, I don't think it should, since that is not the explicit object you are searching for. However, I am not 100% sure that would be the _universally_ expected behavior. It isn't really an issue I just hadn't convinced myself of this fact yet. I will probably just go ahead and implement it this way though and then see if people reach for the pitchforks. It shouldn't be very involved.

```fortran
MODULE test_mod
TYPE :: test_parent
CONTAINS
  PROCEDURE :: foo => parent_foo
END TYPE test_parent
!
TYPE,  EXTENDS(test_parent) :: test_child
CONTAINS
  PROCEDURE :: foo => child_foo
END TYPE test_child
END MODULE test_mod
!
PROGRAM test_prog
USE test_mod
IMPLICIT NONE
TYPE(test_parent) :: obj1
TYPE(test_child) :: obj2

CALL obj1%foo()
CALL obj2%foo()

END PROGRAM test_prog
```

**Comment by mscfd** [comment]
Indeed ```test_parent::foo``` should not be mentioned. On the other hand, I guess one should be careful with type versus class. Lets say I look for foo from obj1, which I know to be of type (not of class) test_parent (cursor position at ```call obj1%foo()```), then I can also exclude foo from test_child, as foo was overwritten. On the other hand, if obj1 is of ```class(test_parent)``` instead of ```type(test_parent)```, then I should include foo from test_child and hence the line ```call obj2%foo()``` should be among the listed references.

**Comment by mscfd** [comment]
Great, works fine!
