### ISSUE TITLE
Parsing failed

### ISSUE THREAD

**Issue by dpo** [hansec/fortran-language-server#9]
I installed this and atom ide-fortran on OSX but all I get is a lot of "parsing failed" error messages (one per file in the project). Any idea what's going on?

![screen shot 2018-04-11 at 16 19 15](https://user-images.githubusercontent.com/38760/38622737-22437ebe-3da4-11e8-9a44-dbdbd8b6c861.png)

**Comment by hansec** [comment]
Can you run the parser in [debug mode](https://github.com/hansec/fortran-language-server/wiki/Debugging-parser-errors) on one of the files? Since you get an error for every file I suspect there is some common syntax feature that is tripping up the parser. I will try and take a look myself as well since it looks like the source code is freely available.

**Comment by dpo** [comment]
Thanks. Here's what I obtain:
```
$ fortls --debug_parser --debug_filepath=qr_mumps-2.0/src/solve/qrm_apply.F90 

Testing parser
  File = "qr_mumps-2.0/src/solve/qrm_apply.F90"
  Detected format: free

=========
Parser Output
=========

Traceback (most recent call last):
  File "/Users/dpo/Library/Python/2.7/bin/fortls", line 9, in <module>
    load_entry_point('fortran-language-server==0.3.2', 'console_scripts', 'fortls')()
  File "build/bdist.macosx-10.12-intel/egg/fortls/__init__.py", line 75, in main
  File "build/bdist.macosx-10.12-intel/egg/fortls/parse_fortran.py", line 497, in process_file
AttributeError: 'NoneType' object has no attribute 'add_use'
```

**Comment by hansec** [comment]
Ok, it looks like the parser is having issues with subroutine, module, and other object names starting with an underscore. I will try to get a fix for this in the next few days. Thanks for the report!
