### ISSUE TITLE
References are missing for type bound procedures

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#94]
For the code below, the following two requests are missing references:
```fortls --debug_rootpath . --debug_references --debug_filepath test2.f90 --debug_line 11 --debug_char 12```

```fortls --debug_rootpath . --debug_references --debug_filepath test2.f90 --debug_line 17 --debug_char 12```

The first asks for references of subroutine car, the second for references of dar. The answer has only the subroutine and end subroutine lines. But it should also contain the reference in the type definition mytype, and in my opinion, it should also contain any usage of these type bound procedures (call self%car and call self%dar).

Related to #88.

```
module mod

type mytype
contains
   procedure, public :: car => car
   procedure, public :: dar
end type mytype

contains

subroutine car(self, i)
   class(mytype) :: self
   integer :: i
   call self%dar(real(i))
end subroutine car

subroutine dar(self, r)
   class(mytype) :: self
   real :: r
   call self%car(int(i))
end subroutine dar

end module mod
```

**Comment by mscfd** [comment]
As a sidenote: If I ask for definition of type-bound procedure car or dar via
```
fortls --debug_rootpath . --debug_definition --debug_filepath test2.f90 --debug_line 5 --debug_char 25
```
```
fortls --debug_rootpath . --debug_definition --debug_filepath test2.f90 --debug_line 6 --debug_char 25
```

I get the line themselves. I would rather expect to get the "subroutine car" and "subroutine dar" lines. In fact, currently I do not know what to ask for to jump from the type bound procedure declaration to the definition of the subroutine/function itself, if these have the same name.

**Comment by hansec** [comment]
Thanks for the report. It looks like symbol differentiation when objects have the same name needs to be improved. I think this will fix the "sidenote" case too.

There is a [GoTo Implementation](https://microsoft.github.io/language-server-protocol/specification#textDocument_implementation) request that I can implement that would allow you to jump straight to `subroutine dar` from `call self%dar` statements. However, I am not sure if it is universally implemented in editors since it is part of the newer v3 specification. Other then that there is no way to jump from the `procedure, public :: dar` line to its implementation since there are two symbols that match the "definition" request, making things ambiguous.

As for `call self%dar` results in find references requests for `subroutine dar`. The specification is generally more "symbol" based in which case the symbol referenced by `%dar` is the type-bound method and not its implementation so generally the find results would not "flow through" that link. Personally, I think this way makes things a little more explicit and doesn't really add unnecessary steps.

**Comment by mscfd** [comment]
Thanks a lot. Works fine. As I just saw emacs has an lsp-goto-implementation function, which does the job. It is often rather confusing to find out which of the many packages within emacs does which job. I have not yet figured out signature help in emacs. All in all, the current state of fortls and emacs already helps a lot in navigating within a big code base. From what I saw, there still seem to be a number of minor issues (completition lists).
