### ISSUE TITLE
Properly extract dimension (and len) specification if it contains parenthesis

### ISSUE THREAD

**Issue by mscfd** [hansec/fortran-language-server#97]
The following kind of constructs are used occasionally, but are not parsed correctly:

real, dimension(1:ubound(some_arg,1),1:ubound(some_arg,2)+2) :: tmp
character(len=len(strarg1)+len(strarg2)) :: str

There are some places where the parenthesised part is extracted with find() method of string, such as in:
```
def get_var_dims(test_str):
    i1 = test_str.find('(')
    i2 = test_str.find(')')
    ...
```
This strategy obviously fails if the parenthesised part itself contains parenthesis.

**Comment by mscfd** [comment]
BTW, I came across this problem because I was looking for where and why the order of modifiers is changed. Is there any particular reason to do a 
```
modifiers.sort()
```
at the end of ```def map_keywords()``` in objects.py?
It is just that I like to keep the order of modifiers I have used myself when seeing hover-documentation.

**Comment by hansec** [comment]
Thanks for the report. I have updated the code to use more thorough parenthesis matching. Let me know if you continue to see issues of this type.

As for the sorting this was just a personal preference to have things laid out consistently. I have now added an option to preserve the original order. Both this and the fix for the original issue will be included in the next release.
